[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.13.1"
tokio = { version = "1.45.0", features = ["full"] }
proto = {path="../proto"}

log = { version = "0.4.27", features = ["std", "serde"] }
env_logger = "0.11.8"
