filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/**/*.log
    json.keys_under_root: true
    json.add_error_key: true
output.elasticsearch:
  hosts: ["http://host.docker.internal:9200"]
  username: "${ELASTIC_USERNAME:elastic}"
  password: "${ELASTIC_PASSWORD:password}"  # Leave blank if xpack security is disabled

setup.kibana:
  host: "http://kibana:5601"

setup.ilm.enabled: false
