datanode_id: "datanode_0"
namenode_addrs: "http://host.docker.internal:7000"
internal_grpc_port: "3000"
internal_tcp_port: "3001"
external_grpc_addrs: "http://127.0.0.1:3000"
external_tcp_addrs: "127.0.0.1:3001"
storage_path: "./temp/store"
log_level: trace
log_base: ./temp/datanode/ 
apm_endpoint: http://127.0.0.1:8200/v1/traces
