[package]
name = "proto"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.13.1"
tokio = { version = "1.45.0", features = ["full"] }
prost = "0.13.5"

[build-dependencies]
tonic-build = "0.13.1"

