id: namenode 
internal_grpc_port: "7000" 
external_grpc_addrs: http://127.0.0.1:7000,
ledger_file: /app/history.log  
log_level: trace 
log_base: /app/logs/
state_log_file: /app/logs/state.log
apm_endpoint: http://host.docker.internal:8200/v1/traces
api_port: 8080
api_jwt_sign_key: nothing to secure route is read only
